- .github/workflows/rust.yml
- Makefile
- bin/ream/src/main.rs
@varun-doshi
anyone can review this.
Anyways since our CI required the nightly flag to work with our `rustfmt.toml` options
> fix: ci/(make lint) fmt requires nightly to function properly with rustfmt.toml

- .github/workflows/rust.yml
- testing/ef-tests/README.md
we weren't running tests for consensus spec tests, and also not running tests for the whole workspace
> chore(ci): fix test ci

- crates/common/consensus/src/deneb/beacon_state.rs
- crates/common/consensus/src/fork_choice/helpers/constants.rs
- crates/common/consensus/src/misc.rs
I added a few beacon functions, get_seed, get_committee_count_per_slot and get_beacon_proposer_index and I'm currently working on implementing even more
> feat: added beacon functions

- crates/common/consensus/src/deneb/beacon_state.rs
- crates/common/consensus/src/fork_choice/helpers/constants.rs
Added `BeaconState` mutators and functions
> feat: add BeaconState functions/mutators

- crates/common/consensus/src/deneb/beacon_state.rs
`saturating_sub` doesn't mutate the lhs value, so let it mutate
> fix: make `decrease_balance` work

- crates/common/consensus/src/deneb/beacon_state.rs
1. `operation_objects` is read-only, so those could be just a reference.
2. `process_operations` has some misleading variable name, so fixed those.
> fix: nit block operations

- crates/common/consensus/src/deneb/beacon_state.rs
This could affect verification result, so replace the correct one.
Refer to [eth2book](https://eth2book.info/capella/part3/helper/crypto/#bls-signatures)
> fix: make DST correct

- crates/common/consensus/src/deneb/beacon_state.rs
I found this issue while integrating with EF tests. `validator.activation_epoch` can be the max of `u64`.
> fix: check overflow at `process_voluntary_exit`

- crates/common/consensus/src/deneb/beacon_state.rs
- testing/ef-tests/tests/tests.rs
1. `apply_deposit` should ignore the corresponding deposit when pubkey is in wrong format.
2. `add_validator_to_registry` should append new entry for the corresponding validator to `previous_epoch_participation`, `current_epoch_participation`, and `inactivity_scores`. This was added at Altair fork. ([Link](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/beacon-chain.md#modified-add_validator_to_registry))
I added `test_operation!` for `process_deposit`, to check whether I correctly write the code.
> feat: update `apply_deposit` and `add_validator_to_registry` to altair changes

- crates/common/consensus/src/deneb/beacon_state.rs
- testing/ef-tests/Makefile
- testing/ef-tests/src/macros/mod.rs
- testing/ef-tests/src/macros/operations.rs
- testing/ef-tests/src/macros/ssz_static.rs
- testing/ef-tests/tests/tests.rs
We are trying to support all the `consensus-spec-tests`, I looked at the work @syjn99 was doing and wanted to instead target testcases which are more minimal and slowly work my way up to the more complex test cases, as then it should be smoother to progressively support more test cases.
I got the operation `Withdrawals` tests working.
I found 2 bugs
- We weren't decoding the addresses properly
- We were doing `if X == 0`, when the spec asked for `if X != 0`
After I fixed these 2 problems, the `process_withdrawal` tests started passing :rocket: 
Lets keep knocking these tests out :fire:
> fix: process_withdrawals and add corresponding ef-tests

- .github/workflows/rust.yml
- testing/ef-tests/Makefile
As we add more tests running them in debug mode takes a lot of time, I was running https://github.com/ReamLabs/ream/pull/108 in debug mode and it took quite a bit to finish, running the tests in release mode helped a lot
> ci: run rust tests in release mode

- Cargo.lock
- Cargo.toml
- crates/common/consensus/Cargo.toml
- crates/common/consensus/src/deneb/execution_payload.rs
- crates/common/consensus/src/execution_engine/mod.rs
- crates/common/consensus/src/execution_engine/new_payload_request.rs
- crates/common/consensus/src/lib.rs
- crates/common/consensus/src/withdrawal.rs
Implemented the is_valid_block_hash, is_valid_versioned_hashes functions 
https://ethereum.github.io/consensus-specs/specs/deneb/beacon-chain/#is_valid_block_hash
https://ethereum.github.io/consensus-specs/specs/deneb/beacon-chain/#is_valid_versioned_hashes
> feat: Implemented the is_valid_block_hash, is_valid_versioned_hashes functions

- testing/ef-tests/tests/tests.rs
This PR adds some operation tests that are currently passing the cases.
- `process_voluntary_exit`
- `process_bls_to_execution_change`
> test: add operation tests for `process_voluntary_exit` & `process_bls_to_execution_change`

- crates/common/consensus/src/deneb/beacon_state.rs
implemented the kzg_commitment_to_versioned_hash function
https://ethereum.github.io/consensus-specs/specs/deneb/beacon-chain/#kzg_commitment_to_versioned_hash
> feat: implemented the kzg_commitment_to_versioned_hash function

- crates/common/consensus/src/deneb/beacon_state.rs
- testing/ef-tests/tests/tests.rs
- Fixed participation flags shifting issue.
- Applied [EIP-7045](https://eips.ethereum.org/EIPS/eip-7045), which removes the inclusion delay consideration from Deneb.
- Added EF test for `process_attestation`
> fix: update `process_attestation` for deneb

- crates/common/consensus/src/deneb/beacon_state.rs
- testing/ef-tests/tests/tests.rs
We now need two operation tests:
- `process_sync_aggregate`
- `process_execution_payload`: Not implemented yet
It seems like `process_sync_aggregate` has some problem. I would open an issue for this.
> test: add more opertation tests

- crates/common/consensus/src/execution_engine/mod.rs
This is required to implement process_execution_payload() https://github.com/ReamLabs/ream/issues/51
implementing json engine api rpc calls
> feat: implenent engine_exchange_capabilities json engine api rpc call

- crates/common/consensus/src/execution_engine/mod.rs
- crates/common/consensus/src/execution_engine/rpc_types/forkchoice_update.rs
- crates/common/consensus/src/execution_engine/rpc_types/mod.rs
This PR must be merged after https://github.com/ReamLabs/ream/pull/123
Implemented this issue in this PR https://github.com/ReamLabs/ream/issues/120
This is required to implement process_execution_payload() https://github.com/ReamLabs/ream/issues/51
implementing json engine api rpc calls
> feat: implement engine_forkchoiceUpdatedV3 api rpc call

- crates/common/consensus/src/execution_engine/mod.rs
- crates/common/consensus/src/execution_engine/rpc_types/get_blobs.rs
- crates/common/consensus/src/execution_engine/rpc_types/mod.rs
This is required to implement process_execution_payload() https://github.com/ReamLabs/ream/issues/51
implementing json engine api rpc calls
> feat: implement engine_getBlobV1 api rpc call

- Cargo.lock
- Cargo.toml
- bin/ream/Cargo.toml
- bin/ream/src/cli/mod.rs
- crates/common/network_spec/Cargo.toml
- crates/common/network_spec/src/cli.rs
- crates/common/network_spec/src/lib.rs
- crates/common/network_spec/src/networks.rs
Just the basic for adding multi network support. We will specify hardfork timestamps and such in the NetworkSpec. Any network specific configurations will belong here. As we build our client out the idea will be to for example 
```
if network.is_electra_enabled(timestamp) {
// do xyz
}
```
by adding this now hopefully this gives everybody an idea and as we build the puzzle pieces will fall into place around this
> feat: add network cli for specifying network specification

- crates/common/consensus/src/deneb/beacon_state.rs
- testing/ef-tests/src/macros/operations.rs
The todo was removed in the last PR, but basically we weren't running operation tests which used bls, I fixed the bug so now the test suite works with BLS tests enabled
> fix: `is_valid_indexed_attestation` and enable bls tests for operation tests

- crates/common/consensus/src/deneb/beacon_state.rs
@syjn99 said these don't work when he tries to use them in consensplus, I ran ef-tests and they passed without them
> fix: remove serde for VariableList/FixedVector from BeaconState

- .github/workflows/rust.yml
I added support for compiling to risc0
Issue: https://github.com/ReamLabs/ream/issues/147
> feat: add CI that ream-consensus and ream-bls compiles to risc0

- testing/ef-tests/tests/tests.rs
It seemed that the get_inactivity_penalty_deltas() function was implemented in a later spec then what was implemented 
Issue: https://github.com/ReamLabs/ream/issues/161
> feat: implemented epoch processing test for process_rewards_and_penalties()

- bin/ream/src/main.rs
- crates/networking/discv5/src/config.rs
- crates/networking/discv5/src/discovery.rs
- crates/networking/p2p/src/network.rs
Discv5 doesn't find any peers in the current setting. This PR adds bootnodes to the discv5 service and now 16 peers are found.
> fix: no discovered peers in discv5

- .github/workflows/riscv.yml
CI was failing on my db PR #249 due to Risc0 changing how they install the default toolchain here is a link to the failing CI https://github.com/ReamLabs/ream/actions/runs/14076476787/job/39420262633?pr=249 which throws an error giving instructions on what we should do instead now.
In short `rzup install` now also does what `cargo risczero install` used to do, which install the latest toolchain
> fix(ci): risc0 changed how toolchain is installed

- README.md
> docs: fix broken telegram link in README.md

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/docs.yml
- .github/ISSUE_TEMPLATE/feature.yml
- SECURITY.md
The PR adds minimal issue templates that should faciliate contributions in a structured fashion.
New issues can be easily filtered by `S-needs-triage` for maintainers to triage them. (More on [triage](https://bevyengine.org/learn/contribute/reference/triage))
In order to complete this setup, we need to set up a discussions and make a security email account.
Note: the templates are heavily inspired by Ithaca's.
> docs: add issue templates

- bin/ream/src/cli/mod.rs
- bin/ream/src/main.rs
- crates/networking/p2p/src/bootnodes.rs
@Vid201 ping for review
@Vid201 wanted a way for the user to specify which bootnodes to connect to through the CLI. Initially he tried in this PR https://github.com/ReamLabs/ream/pull/253 to  extend the pre-existing list, but I would prefer fleshed out approach if we are going to add a bootnodes cli. I message him and he said it is fine if I make a PR for this
> feat: add bootnodes cli param

- .github/workflows/rust.yml
- Makefile
Adding a CI which makes sure our `Cargo.toml` files are sorted, we are using `cargo-sort` for this which was added to our makefile and Ream book recently. Since it is included in `make lint` we should have a ci for it
> ci: add CI which runs cargo sort --check

- Cargo.lock
- crates/storage/Cargo.toml
- crates/storage/src/tables/beacon_state.rs
- crates/storage/src/tables/mod.rs
updated beacon state table to use block_root instead of slot number
> feat: updated beacon state table to use block_root instead of slot number

- crates/storage/src/db.rs
- crates/storage/src/tables/mod.rs
- crates/storage/src/tables/unrealized_justifications.rs
fixes https://github.com/ReamLabs/ream/issues/272
added the unrealized justifications table to the database
> feat: add unrealized justifications table to the database

- crates/storage/src/db.rs
- crates/storage/src/tables/mod.rs
- crates/storage/src/tables/proposer_boost_root.rs
fixes https://github.com/ReamLabs/ream/issues/277
added the proposer_boost_root table to the database
> feat: add proposer_boost_root table to the database

- crates/storage/src/db.rs
- crates/storage/src/tables/equivocating_indices.rs
- crates/storage/src/tables/mod.rs
fixes https://github.com/ReamLabs/ream/issues/276
added the equivocating_indices table to the database
> feat: add equivocating_indices table to the database

- Cargo.lock
- crates/storage/Cargo.toml
- crates/storage/src/db.rs
- crates/storage/src/tables/beacon_block.rs
- crates/storage/src/tables/mod.rs
- crates/storage/src/tables/slot_index.rs
- crates/storage/src/tables/state_root_index.rs
Implements the following tables: 
- Slot -> Block root (u64->B256)
- State Root -> Block Root (B256 -> B256)
Both required for Beacon APIs
> feat: implement slot and state root index tables

- .github/workflows/core-rust.yml
- .github/workflows/optional-rust.yml
- .github/workflows/riscv.yml
If these CI's fail we want the `merge-queue` to stop a PR from being merged. This can be helpful if we are merging multiple PR's in the same queue and an interaction between the different PR's cause's a critical CI to fail.
Documentation on `merge_group` can be found here https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
This PR doesn't require `cargo-udeps` to pass I view it as not as critical as the other CI's
> chore: set CI's which must pass to be merged

- crates/rpc/src/handlers/state.rs
- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/routes/debug.rs
- crates/rpc/src/routes/mod.rs
- crates/rpc/src/types/id.rs
wip closes #176 
This PR introduces
- Allow `state_id` to be passed as strings `head`, `justified`, `finalized`, `genesis`
- Creates a new base url with `eth/v2/...`
- Return BeaconState from the api endpoint implemented
> feat: implement /eth/v2/debug/beacon/states/{state_id}

- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/types/id.rs
- crates/rpc/src/utils/error.rs
- crates/storage/src/db.rs
Fixes an issue where the endpoints return `500 Internal Error` instead of `400 Not Found`
The issue: None of the tables were actually ever created since we never insert data(yet).
This fix will make it so that even if we dont insert data, it will atleast show StatusCode:400 instead of 500 which is a better output
> fix: api returns 500 internal error

- crates/rpc/src/handlers/block.rs
- crates/rpc/src/handlers/header.rs
- crates/rpc/src/handlers/mod.rs
- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/types/query.rs
```
cargo run node
```
```
/beacon/headers
```
With optional params:
```
/beacon/headers?slot=123&parent_root=0x04567
```
Closes #196
> feat: implement /headers

- crates/rpc/src/handlers/block.rs
closes #225 
This PR adds the following changes
- Functions to calculate rewards in a block from attestations, sync committees and slashings
- Total rewards as a sum of above 3
The API endpoint for this issue is the same as the one implemented in PR #324 , remaining is the function to calculate rewards.
According to Beacon api specs, this api is shown twice, once under `beacon` group and another under `rewards` group.
> feat: implement /eth/v1/beacon/rewards/blocks/{block_id}

- crates/crypto/bls/src/pubkey.rs
- crates/rpc/src/handlers/validator.rs
- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/types/id.rs
* Closes [Implement /eth/v1/beacon/states/{state_id}/validator_identities #190](https://github.com/ReamLabs/ream/issues/190)  
* This pull request implements the Beacon API endpoint:  **POST** `/eth/v1/beacon/states/{state_id}/validator_identities`  
* Response data contains **no duplicate entries** and is **sorted by index** in ascending order.
* Octet (SSZ) response is not supported, consistent with `/eth/v2/beacon/blocks/{block_id}` and `/eth/v2/debug/beacon/states/{state_id}`. It appears the main SSZ implementation for response data doesn't exist yet?
* The spec: [https://ethereum.github.io/beacon-APIs/#/Beacon/postStateValidatorIdentities](https://ethereum.github.io/beacon-APIs/#/Beacon/postStateValidatorIdentities)
> **Note**: Without the mocked data, the current behavior returns …
> feat: implement /eth/v1/beacon/states/{state_id}/validator_identities

- Cargo.lock
- Cargo.toml
- crates/common/node/Cargo.toml
- crates/common/node/build.rs
- crates/common/node/src/version.rs
- crates/networking/p2p/src/network.rs
Just doing some dependency maintenance, I wanted to bump the Rust version as a feature I am trying to use stabilizes in 1.87, but we   need to wait for Risc0 to bump their version for the zkvm first 
bump all the libraries
> chore: bump libraries to latest major/minor version

- bin/ream/src/main.rs
- crates/common/network_spec/src/networks.rs
- crates/rpc/src/handlers/block.rs
- crates/rpc/src/handlers/config.rs
- crates/rpc/src/lib.rs
We are going to passing NetworkSpec everywhere, it is something we would only be setting at configuration so we can use a OnceLock, to initialize the global then use it.
Switching to `OnceLock` instead of passing a Arc<> everywhere
> feat: make NetworkSpec a global, instead of passing it everywhere

- Cargo.lock
- crates/crypto/merkle/Cargo.toml
- crates/crypto/merkle/src/hash.rs
- crates/crypto/merkle/src/index.rs
- crates/crypto/merkle/src/lib.rs
- crates/crypto/merkle/src/multiproof.rs
This PR adds a [multiproof](https://github.com/ethereum/consensus-specs/blob/dev/ssz/merkle-proofs.md#merkle-multiproofs) feature in our merkle package, `ream-merkle`. This feature will be used in passing `BeaconState` partially to the zkVM.
For general understanding, reading [my note](https://hackmd.io/@reamlabs/B1SJuEoxle#Merkle-Multiproof) might be helpful. Also, you can see an [example](https://hackmd.io/@reamlabs/B1SJuEoxle#Example-first) of using this multiproof.
It modifies slightly the code from [`ssz_rs`](https://github.com/ralexstokes/ssz-rs/blob/main/ssz-rs/src/merkleization/multiproofs.rs) which implements the Python-like [spec code](https://github.com/ethereum/consensus-specs/blob/dev/ssz/merkle-proofs.md#merkle-multiproofs) into Rust.
> feat: add multiproof feature in `ream-merkle`

- Cargo.lock
- bin/ream/Cargo.toml
- bin/ream/src/cli/mod.rs
- bin/ream/src/main.rs
- crates/common/checkpoint_sync/src/checkpoint.rs
- crates/common/checkpoint_sync/src/lib.rs
- crates/common/consensus/src/constants.rs
- crates/common/network_spec/Cargo.toml
- crates/common/network_spec/src/b32_hex.rs
- crates/common/network_spec/src/cli.rs
- crates/common/network_spec/src/fork_schedule.rs
- crates/common/network_spec/src/lib.rs
- crates/common/network_spec/src/networks.rs
- crates/networking/discv5/src/discovery.rs
- crates/networking/discv5/src/eth2.rs
- crates/networking/p2p/src/bootnodes.rs
- crates/networking/p2p/src/req_resp/inbound_protocol.rs
- crates/networking/p2p/src/req_resp/outbound_protocol.rs
- crates/rpc/src/handlers/block.rs
- crates/rpc/src/handlers/config.rs
Fixes: https://github.com/ReamLabs/ream/issues/394 
I implemented support for reading config.yaml files into the NetworkSpec
In a followup PR I'm going to remove the hardcoded genesis_validators_root, this is required to support networks then mainnet https://github.com/ReamLabs/ream/issues/403
> feat: Add support for reading config.yaml into NetworkSpec

- Cargo.lock
- Cargo.toml
- crates/rpc/Cargo.toml
- crates/rpc/src/handlers/blob_sidecar.rs
- crates/rpc/src/handlers/header.rs
- crates/rpc/src/handlers/state.rs
- crates/rpc/src/handlers/validator.rs
- crates/rpc/src/types/query.rs
Fixes #405
Some `GET` endpoints were using `Json` as their input which meant they need be passed in the `body` section of the request. As per spec, these endpoints should only have `Path` and `Query` types in the request i.e. the endpoints should look something like this:
```
http://localhost/eth/v1/beacon/blob_sidecars/head?indices=1&indices=4
```
But these were failing in Ream since they were in `Json` format. 
Solely switching from `Json` to `Query` type in `actix-web` does not do the trick because `actix` does not support duplicate name keys in the query as per this [discussion](https://github.com/actix/actix-web/issues/1301) .
Hence the only way to format it as per spec is to implement a custom deserializer ourselves(which I've done and changed it to a macro for ease of use).
Note: …
> feat: fix Beacon API content type

- bin/ream/src/main.rs
- crates/common/consensus/src/constants.rs
- crates/networking/discv5/src/discovery.rs
- crates/networking/p2p/src/network.rs
- crates/networking/p2p/src/req_resp/inbound_protocol.rs
- crates/networking/p2p/src/req_resp/outbound_protocol.rs
- crates/rpc/src/handlers/block.rs
- crates/storage/src/tables/beacon_state.rs
Fixes: https://github.com/ReamLabs/ream/issues/403
https://doc.rust-lang.org/std/sync/struct.OnceLock.html
Replaced the hardcoded MAINNET_GENESIS_VALIDATORS_ROOT constant with a dynamically initialized genesis_validator_spec() on start up.
> feat: dynamically initialized genesis_validators_root on start up, instead of using a hardcoded constant

- crates/common/checkpoint_sync/src/lib.rs
Improve logging during checkpoint sync. The state can take some time to download and at the moment it feels like the Ream node freezes.
Added some logs.
> chore: improve checkpoint sync logs

- Cargo.lock
- Cargo.toml
- bin/ream/Cargo.toml
- bin/ream/src/cli.rs
- bin/ream/src/main.rs
- crates/common/beacon_chain/Cargo.toml
- crates/common/beacon_chain/src/beacon_chain.rs
- crates/common/beacon_chain/src/lib.rs
- crates/common/consensus/src/electra/beacon_state.rs
- crates/common/execution_engine/src/lib.rs
- crates/common/fork_choice/src/handlers.rs
- crates/common/fork_choice/src/store.rs
- crates/networking/manager/Cargo.toml
- crates/networking/manager/src/config.rs
- crates/networking/manager/src/lib.rs
- crates/networking/manager/src/service.rs
- crates/networking/p2p/src/channel.rs
- crates/networking/p2p/src/lib.rs
- crates/networking/p2p/src/network.rs
- crates/networking/p2p/src/req_resp/messages/beacon_blocks.rs
- crates/networking/syncer/Cargo.toml
- crates/networking/syncer/src/block_range/mod.rs
- crates/networking/syncer/src/lib.rs
- crates/rpc/src/config.rs
- crates/rpc/src/lib.rs
- testing/ef-tests/src/macros/fork_choice.rs
- testing/ef-tests/src/macros/operations.rs
- testing/ef-tests/src/macros/sanity_blocks.rs
We want to be able to 
- handle inbound + outbound P2P messages
- make requests to the P2P layer for data so we can sync
- be able to handle on gossip events
There are a lot of people working on the P2P layer right now, this is the foundation so we can all work in parallel. Nothing is set in stone, but this should be enough so we don't bud heads. Normally I would propose this PR when I have a lot more done, but due to splitting work there is a high amount of value getting this in now 
- Create a NetworkManager service which basically coordinates the operations of the Beacon Node
- Add BeaconChain an object which manages the chain
- Syncer crate where we will implement syncers 
- I added the interop between the NetworkManager/Syncers/P2P Layer
> feat: add structure for NetworkManager + BlockByRange syncer

- crates/common/consensus/src/electra/beacon_state.rs
fixes https://github.com/ReamLabs/ream/issues/435
This PR adds the method for voting_period_start_time to BeaconState.
The intention is to use it for get_eth1_vote
> Added voting_period_start_time

- crates/rpc/src/handlers/header.rs
- crates/rpc/src/routes/beacon.rs
Closes #197 
Adds endpoint for fetching header based on block root.
[Spec](https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockHeader)
Can be called using:
```
http://127.0.0.1:5052/eth/v1/beacon/headers/<block_id>
```
> feat: impl /headers/{block_id} endpoint

- .github/workflows/core-rust.yml
These tests take so long to run sequentially
run them in parallel of one another
> ci: split common and ef-tests

- crates/common/validator/src/sync_committee.rs
I implemented the process_sync_committee_contributions method as per the Altair Honest Validator Spec.
Fixes #410 
I reviewed the pseudocode provided in the [Altair Validator Spec](https://github.com/ethereum/consensus-specs/blob/a94d85bb3b33f84a5830eb98945b790b02ae80e8/specs/altair/validator.md#sync-committee-1
)
I created the necessary struct [SyncCommitteeContribution](https://github.com/ethereum/consensus-specs/blob/a94d85bb3b33f84a5830eb98945b790b02ae80e8/specs/altair/validator.md#synccommitteecontribution) as per the spec with appropriate types.
I chose aggregation_bits as BitVector<U64> as the constants were u64. Please let me know if a different type is more appropriate.
> feat: implement process_sync_committee_contributions

- crates/common/validator/src/constants.rs
- crates/common/validator/src/contribution_and_proof.rs
- crates/common/validator/src/sync_committee.rs
…roof_signature
Fixes #412
Implement get_contribution_and_proof and get_contribution_and_proof_signature based on the Altair Honest Validator Spec:
https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/validator.md#broadcast-sync-committee-contribution
This also required the get_sync_committee_selection_proof method and has been implemented as per the Altair Honest Validator Spec:
https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/validator.md#aggregation-selection
> feat: implement get_contribution_and_proof and get_contribution_and_proof_signature

- crates/common/validator/src/aggregate_and_proof.rs
Fixes #413
Implemented the get_aggregate_and_proof and get_aggregate_and_proof_signature functions as per the Phase0 Honest Validator Spec:
https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#broadcast-aggregate
> feat: implement get_aggregate_and_proof and get_aggregate_and_proof_signature

- Cargo.lock
- Cargo.toml
- bin/ream/src/main.rs
- crates/networking/manager/src/service.rs
- crates/networking/p2p/Cargo.toml
- crates/networking/p2p/src/constants.rs
- crates/networking/p2p/src/network.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/handlers/peers.rs
- crates/rpc/src/lib.rs
Resolve [Implement /eth/v1/node/peers/{peer_id} #222](https://github.com/ReamLabs/ream/issues/222)
- **New route** – Added `GET /node/peers/{peer_id}` to align with the beacon-node API spec.  
- **Input validation** – `peer_id` is parsed with `libp2p::PeerId::from_str`; invalid IDs fail fast with `ApiError::BadRequest`.  
- **Response shape** – Returns JSON-wrapped `PeerData`  
```json
{
"peer_id": "<peer_id>",
"enr": null,
"last_seen_p2p_address": "<p2p_address>",
"state": "connected",
"direction": "outbound"
}
- **Error handling** – Parsing and lookup errors map to `ApiError::{BadRequest, NotFound, InternalError}` and are logged via `tracing` for easier debugging.  
- **Stub data source** – Introduced `mock_fetch_peer` as a temporary stand-in; it supplies hard-coded peer info while we …
```
> feat: Implement /eth/v1/node/peers/{peer_id}

- crates/common/consensus/src/electra/beacon_state.rs
- crates/common/validator/src/validator.rs
- crates/rpc/src/handlers/duties.rs
- crates/rpc/src/handlers/mod.rs
- crates/rpc/src/routes/mod.rs
- crates/rpc/src/routes/validator.rs
- crates/rpc/src/types/response.rs
Implement the Beacon API endpoint GET /eth/v1/validator/duties/proposer/{epoch} to allow validator clients to retrieve proposer duty assignments for a specified epoch. 
This endpoint enables validators to query which validator index is assigned to propose blocks for each slot in the given epoch. This is the first endpoint called by a validator in the validator flow.
Fixes #230 
https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/getProposerDuties
The logic implemented:
For each slot in the epoch, find the proposer index of that slot, find it's pubkey, make the ProposerDuty for struct for that slot and send it in the response.
I created the DutiesResponse struct in the beacon response as it has a different response structure than other BeaconAPIs.
I then tested it on sepolia on …
> feat: implement get block proposer duties in the beacon node

- Cargo.lock
- crates/crypto/keystore/Cargo.toml
- crates/crypto/keystore/src/hmac.rs
- crates/crypto/keystore/src/lib.rs
Creating the HMAC helper function in order to read off the encrypted keystore files normally generated by any of the staking CLI.
Originally I intended to just do it for sha256, but I noticed it apparently would work for any hash function. I instead generalized it to work with most of the hash functions we already use in the odd case we may need it for something else.
This is meant as a part of the PBKDF2 implementation, so this would be next. Additionally, scrypt requires PBKDF2-HMAC-SHA256, so it's a mandatory function for keystore decryption.
> feat: hmac for pbkdf2

- crates/common/consensus/src/electra/beacon_state.rs
- crates/common/validator/src/validator.rs
- crates/rpc/src/handlers/duties.rs
- crates/rpc/src/routes/validator.rs
Implement the Beacon API endpoint POST /eth/v1/validator/duties/attester/{epoch}  to allow validator clients to retrieve attester duties for a specified epoch and a given set of validator indices. 
Fixes: #228 
https://ethereum.github.io/beacon-APIs/#/Validator/getAttesterDuties
We moved the function get_committee_assignment(epoch, validator_index) into BeaconState as it will be used in multiple places across the codebase.
For every validator in the list requested, we get the validator's public key and then get the committee assignment for it. 
I have tested this by running the ream binary. Results of my test can be found here: 
https://pastebin.com/RzSvRWLG
> feat: implement get_attester_duties in the beacon node

- Cargo.lock
- Cargo.toml
- bin/ream/src/main.rs
- crates/crypto/keystore/src/encrypted_keystore.rs
- crates/networking/manager/Cargo.toml
- crates/networking/manager/src/service.rs
- crates/networking/p2p/src/channel.rs
- crates/networking/p2p/src/config.rs
- crates/networking/p2p/src/lib.rs
- crates/networking/p2p/src/network.rs
- crates/networking/p2p/src/network_state.rs
- crates/networking/p2p/src/peer.rs
- crates/networking/p2p/src/req_resp/handler.rs
- crates/networking/p2p/src/req_resp/messages/beacon_blocks.rs
- crates/networking/p2p/src/req_resp/messages/blob_sidecars.rs
- crates/networking/p2p/src/req_resp/messages/mod.rs
- crates/networking/p2p/src/req_resp/messages/ping.rs
- crates/networking/p2p/src/req_resp/messages/status.rs
- crates/networking/p2p/src/req_resp/mod.rs
- crates/networking/p2p/src/req_resp/outbound_protocol.rs
- crates/networking/p2p/src/utils.rs
- crates/networking/syncer/src/block_range/mod.rs
- crates/rpc/src/handlers/peers.rs
- crates/rpc/src/lib.rs
We want to handle to requests we are sent over the Req Response P2P domain
Implementing handling the responses some in the network service itself, and others which require access to the database in NetworkManager
> feat: handle ReqResp P2P messages in NetworkManager

- crates/common/beacon_api_types/src/lib.rs
- crates/common/beacon_api_types/src/sync.rs
- crates/common/validator/src/beacon_api_client/mod.rs
Fixes #504 
I created the expected response struct `SyncStatus` in the beacon_api_crate.
I then created a function called `get_node_syncing_status` in the beacon_api_client to make the request to a beacon node and parse the json response.
> feat: implement /eth/v1/node/syncing in the validator

- Cargo.lock
- Cargo.toml
- crates/crypto/keystore/Cargo.toml
- crates/crypto/keystore/src/decrypt.rs
- crates/crypto/keystore/src/keystore.rs
- crates/crypto/keystore/src/lib.rs
fixes https://github.com/ReamLabs/ream/issues/510
Adds a method to get actual key pairs from an encrypted keystore, such as those generated with the staking CLI.
The next logical step is to use these key pairs for our validator client.
> feat: add keystore decryption

- crates/common/beacon_api_types/src/duties.rs
- crates/common/beacon_api_types/src/responses.rs
- crates/common/validator/src/beacon_api_client/mod.rs
Fixes #515 
Fixes #514 
Fixes #431 
We make a get request to the beacon node for the spec and parse the response in a NetworkSpec struct.
We make a post request for getting the sync committee duties and parse the response in the newly created SyncCommitteeDutiesResponse and SyncCommitteeDuty struct.
> feat: implement get_config_spec and get_sync_committee_duties in the Validator Beacon Client

- Cargo.lock
- crates/common/beacon_api_types/Cargo.toml
- crates/common/beacon_api_types/src/lib.rs
- crates/common/beacon_api_types/src/validator.rs
- crates/common/validator/src/beacon_api_client/mod.rs
- crates/rpc/src/handlers/validator.rs
Fixes #524 
Fixes #525
We moved the structs for ValidatorData and ValidatorBalance from the rpc crate to the beacon_api_types crate as it is used across rpc and validator.
We then made GET requests as per the Beacon API spec to the below endpoints and parsed their JSON response to the appropriate structs. 
/eth/v1/beacon/states/{state_id}/fork
/eth/v1/beacon/states/{state_id}/validators/{validator_id}
> feat: implement get_state_fork and get_state_validator in the validator

- crates/common/beacon_api_types/src/committee.rs
- crates/common/beacon_api_types/src/lib.rs
- crates/common/validator/src/aggregate_and_proof.rs
- crates/common/validator/src/beacon_api_client/mod.rs
Fixes: #517 
Fixes: #537 
Small PR implementing some of the Beacon API callers required for attesting validators. I aim to finish all the proposer and attester endpoints in an upcoming PR.
Both functions were implemented as per their Beacon API specs:
https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/publishAggregateAndProofsV2 
https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/prepareBeaconCommitteeSubnet
> feat: implement prepare_committee_subnet and publish_aggregate_and_proofs

- Cargo.lock
- crates/common/beacon_chain/Cargo.toml
- crates/common/beacon_chain/src/beacon_chain.rs
- crates/networking/manager/Cargo.toml
- crates/networking/manager/src/service.rs
- crates/networking/p2p/src/network.rs
Fixes: https://github.com/ReamLabs/ream/issues/451
Connected p2p gossip messages to network manager and added respective on_
> feat: Connect p2p gossip messages to network manager and add respective on_*

- crates/common/validator/src/validator.rs
Fixes #541 
We used the beacon_api_client functions to fetch the duties for the validators.
I fetched for current epoch for proposer and sync committee. However the spec suggests fetching for epoch + 1 for the attester duties. 
https://ethereum.github.io/beacon-APIs/validator-flow.md
> feat: implement fetch duties for the validator

- crates/networking/p2p/src/gossipsub/error.rs
- crates/networking/p2p/src/req_resp/error.rs
- crates/networking/p2p/src/req_resp/handler.rs
- crates/networking/p2p/src/req_resp/outbound_protocol.rs
When I tried to send outbound ReqResp messages, the handler would panic with 
```OutboundStreamState should always be present, poll() should not be in parallel```
We were returning before removing the dead outbound streams, update the code to remove the dead stream before returning
> fix: ReqResp handler crashing when handling outbound connection

- crates/common/beacon_api_types/src/block.rs
- crates/common/beacon_api_types/src/error.rs
- crates/common/consensus/src/electra/blinded_beacon_block.rs
- crates/common/validator/src/beacon_api_client/http_client.rs
- crates/common/validator/src/beacon_api_client/mod.rs
Fixes: #483 
Fixes: #543  
I created POST requests in the beacon_api_client to publish a block and to publish a blinded beacon block as per the Beacon API specs:
https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/publishBlockV2
https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/publishBlindedBlockV2
> feat: add publish_block and publish_blinded_block

- crates/common/validator/src/beacon_api_client/mod.rs
fixes https://github.com/ReamLabs/ream/issues/552
Similar to the other items inside the BeaconApiClient for the Validator. I also noticed a small spelling mistake, so I ended up fixing that.
Implement the logic for creating the sync committee message using the block root.
> feat: add get_block_root and fix a small spelling mistake

- crates/common/validator/src/beacon_api_client/mod.rs
Fixes: #536 
I  implemented a GET request the Beacon node as Beacon API spec:
https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/getAggregatedAttestationV2
> feat: add get_aggregated_attestation to the Validator

- crates/common/beacon_api_types/src/request.rs
- crates/common/validator/src/beacon_api_client/mod.rs
fixes https://github.com/ReamLabs/ream/issues/554
Essentially follows the same format as the subscription endpoint.
With this and the other PR, the goal is to fetch the fork and root, use it to produce a committee message, and then publish that committee message. Aggregators also have to be dealt with later.
> feat: added /eth/v1/beacon/pool/sync_committees

- Cargo.lock
- crates/common/beacon_chain/Cargo.toml
- crates/common/beacon_chain/src/beacon_chain.rs
- crates/networking/manager/src/service.rs
- crates/networking/p2p/Cargo.toml
- crates/networking/p2p/src/channel.rs
- crates/networking/p2p/src/network.rs
- crates/networking/p2p/src/network_state.rs
- crates/networking/p2p/src/peer.rs
- crates/networking/p2p/src/req_resp/handler.rs
- crates/networking/p2p/src/req_resp/messages/mod.rs
- crates/networking/p2p/src/req_resp/outbound_protocol.rs
When dialing a peer, the spec says we must follow up with sending a status message
this serves 2 purposes
- find out if the peer is on the same network or not
- see what block the peer is on so we know what range we can download blocks from them for syncing
Send a status message when dialing a peer, once we get a response we consider a peer connected
> feat: send status requests when dialing peers to properly connect with peers

- crates/networking/p2p/src/network.rs
- Currently we only send our first ping to a dialed peer after 5 minutes, but we use ping to figure out if we want to send a meta data request, we want the meta data of connected peers
- Ping just after we send a status request after the dialed peer connects to the swarm
> feat: send  ping on outbound dialed connection

- crates/networking/p2p/src/req_resp/mod.rs
- crates/networking/p2p/src/req_resp/outbound_protocol.rs
When I was trying to request blocks by range I was getting errors, due to the full payload not being ready and we would keep trying to decode the length every time we would check if we got enough data. This was leading to cases where we would either
- decode the current or next payload improperly
Also we were erroring if we got a `ErrorKind::UnexpectedEof`, but this is fine it just means we didn't get enough data yet
Only decode the length once per a piece of content
Don't error if we haven't gotten enough content yet
> fix: failing to BlockBlock requests over p2p

- Cargo.lock
- bin/ream/src/main.rs
- crates/common/executor/Cargo.toml
- crates/common/executor/src/lib.rs
- crates/networking/manager/src/service.rs
- We are currently spawning 3 tokio async runtimes, we should only be spawning 1 runtime
- Only spawn 1 runtime
- shutdown the tokio threads
- shutdown the runtime
> feat: remove excess Runtimes from 3 to 1 + properly shutdown runtime

- crates/common/validator/src/attestation.rs
- crates/common/validator/src/validator.rs
Fixes: #561 
Implements the following portion of the [validator flow](https://ethereum.github.io/beacon-APIs/validator-flow.md): 
> 3. [Fetch AttestationData](#/ValidatorRequiredApi/produceAttestationData)
> 4. [Submit Attestation](#/ValidatorRequiredApi/submitPoolAttestations) (AttestationData + aggregation bits)
- Aggregation bits are `Bitlist` with length of committee (received in AttesterDuty)
with bit on position `validator_committee_index` (see AttesterDuty) set to true
I fetch an attestation data from the beacon node.
I then sign the attestation data and create a single attestation object that we use to submit an attestation.
> feat: implement make attestation

- crates/common/validator/src/aggregate_and_proof.rs
- crates/common/validator/src/attestation.rs
- crates/common/validator/src/validator.rs
Fixes: #562 
We implement the following portion of the [Validator Flow](https://ethereum.github.io/beacon-APIs/validator-flow.md):
>5. If aggregator:
- Wait for `SECONDS_PER_SLOT * 2 / 3` seconds into the assigned slot
- [Fetch aggregated Attestation](#/ValidatorRequiredApi/getAggregatedAttestation) from Beacon Node you've subscribed to your subnet
- [Publish SignedAggregateAndProofs](#/ValidatorRequiredApi/publishAggregateAndProofs)
I check for the keystore for the provided validator index (aggregator_index)
I fetch the aggregated attestation from the beacon node.
I then create an AggregateAndProof object using the aggregate and the selection_proof (I believe this is a slot signature)
I sign this aggregate and proof and publish it using the Beacon API endpoint.
> feat: implement submit_aggregate_and_proof

- crates/common/beacon_api_types/src/duties.rs
- crates/common/beacon_api_types/src/id.rs
- crates/common/consensus/src/bls_to_execution_change.rs
- crates/common/consensus/src/consolidation_request.rs
- crates/common/consensus/src/deposit_data.rs
- crates/common/consensus/src/deposit_message.rs
- crates/common/consensus/src/deposit_request.rs
- crates/common/consensus/src/electra/beacon_state.rs
- crates/common/consensus/src/pending_deposit.rs
- crates/common/consensus/src/sync_committee.rs
- crates/common/consensus/src/validator.rs
- crates/common/consensus/src/withdrawal_request.rs
- crates/common/validator/src/sync_committee.rs
- crates/common/validator/src/validator.rs
- crates/crypto/bls/README.md
- crates/crypto/bls/src/lib.rs
- crates/crypto/bls/src/public_key.rs
- crates/crypto/bls/src/supranational/mod.rs
- crates/crypto/bls/src/supranational/public_key.rs
- crates/crypto/bls/src/supranational/signature.rs
- crates/crypto/bls/src/traits.rs
- crates/crypto/bls/src/zkcrypto/mod.rs
- crates/crypto/bls/src/zkcrypto/public_key.rs
- crates/crypto/bls/src/zkcrypto/signature.rs
- crates/crypto/keystore/src/keystore.rs
- crates/rpc/src/handlers/duties.rs
- crates/rpc/src/handlers/light_client.rs
- crates/rpc/src/handlers/state.rs
- crates/rpc/src/handlers/validator.rs
Currently we are using the shorthand `PubKey` instead of `PublicKey`. This is inconsistent with practices done in the rest of our codebase and also inconsistent with `PrivateKey`. We should just rename it to `PublicKey` so it is more readable.
renaming `PubKey` to `PublicKey`
> refactor: rename PubKey to PublicKey

- .gitignore
It can be annoying to remove DS_Store files if accidentally committed. Best to ignore
> chore: add DS_Store to gitignore

- crates/rpc/src/routes/debug.rs
- crates/rpc/src/routes/mod.rs
Fixes to link `/eth/v2/debug/beacon/heads` with current implementation (`get_beacon_heads`). Refer to [Beacon API Specification](https://ethereum.github.io/beacon-APIs/#/Debug/getDebugChainHeadsV2).
`/eth/v1/debug/fork_choice` (related issue: #221) is the only endpoint that has a path starting with `/eth/v1/debug`, so I simply deleted the `register_debug_routes` as it is not implemented yet.
> fix: register /beacon/heads to /eth/v2/debug

- crates/common/consensus/src/electra/beacon_block.rs
- crates/rpc/src/handlers/block.rs
- crates/rpc/src/routes/beacon.rs
Fixes #207 
Taking most of the data from `SignedBeaconBlock` and using `execution_payload_header` from its execution payload. Then checking for the request header if `application/octet-stream` returning a string response instead of json.
> feat: add endpoint for blinded block

- crates/common/consensus/src/electra/beacon_state.rs
data.index was used instead of committee_index
which caused
```
ensure!(
attestation.aggregation_bits.len() == committee_offset,
"Aggregation bits length must match committee size"
"Aggregation bits length must match committee size {} != {}",
attestation.aggregation_bits.len(),
committee_offset
);
```
To fail when I was executing blocks
Use the correct index
> fix: wrong index was used in process_attestation

- crates/common/consensus/src/electra/beacon_state.rs
Processing an epoch takes forever
don't calculate get_unslashed_participating_indices every loop interation
> perf: don't recalculate unslashed_participating_indices redundantly

- .github/workflows/riscv.yml
- Cargo.toml
- book/SUMMARY.md
- book/cli/SUMMARY.md
- book/cli/ream.md
- book/cli/ream/lean_node.md
- crates/common/checkpoint_sync/src/lib.rs
- crates/common/consensus/beacon/src/electra/beacon_state.rs
- crates/common/consensus/misc/src/misc.rs
- crates/common/fork_choice/src/store.rs
- crates/common/validator/beacon/src/attestation.rs
- crates/common/validator/beacon/src/sync_committee.rs
- crates/common/validator/beacon/src/validator.rs
- crates/networking/manager/src/gossipsub/validate/blob_sidecar.rs
- crates/networking/p2p/src/network/beacon.rs
- crates/networking/p2p/src/req_resp/handler.rs
- crates/networking/p2p/src/req_resp/outbound_protocol.rs
- crates/rpc/beacon/src/handlers/identity.rs
- crates/rpc/beacon/src/handlers/validator.rs
Rust `1.88.0` is now stable. ([changelog](https://releases.rs/docs/1.88.0/)) I wanted to use let-chain because it makes the code cleaner.
Bump Rust version to `1.88.0` and fix linting issue when I run `make lint`.
Also I forgot to update our book 😂, this PR also introduces a new command `lean_node` in our book.
> chore: bump rust version to 1.88 & make linter happy

- crates/common/beacon_api_types/src/error.rs
- crates/common/beacon_api_types/src/query.rs
- crates/common/fork_choice/src/store.rs
- crates/rpc/beacon/src/handlers/validator.rs
- crates/rpc/beacon/src/routes/validator.rs
Missing attestation_data validator endpoint for the electra hardfork.
- I have added some helper functions on the unrealized_checkpoint_table and justified_checkpoint_table to get the checkpoint details.
- Created a new request type for the API endpoint.
- Fetched data from the checkpoints table and highest block root from the slot index table. And returned the data object
- Logic Verification
> feat: implement /eth/v1/validator/attestation_data

- crates/common/fork_choice/src/store.rs
- crates/common/operation_pool/src/lib.rs
- crates/rpc/beacon/src/handlers/prepare_beacon_proposer.rs
Closes #634
This PR implements automatic epoch-based expiration for proposer preparation data according to the beacon API specification. Proposer preparations now persist through the submission epoch plus 2 additional epochs (3 epochs total) before automatic cleanup.
1. **Enhanced data structure** (`crates/common/operation_pool/src/lib.rs`)
- Added `ProposerPreparation` struct to track `fee_recipient` and `submission_epoch`
- Modified storage to capture epoch information at submission time
2. **Cleanup mechanism** (`crates/common/operation_pool/src/lib.rs`)
- Added `clean_proposer_preparations(current_epoch)` method
- Retains preparations where `current_epoch <= submission_epoch + 2`
3. **Automatic cleanup integration** (`crates/common/fork_choice/src/store.rs`)
- Integrated cleanup into …
> feat: Implement epoch-based expiration for prepare_beacon_proposer

- crates/common/validator/beacon/src/validator.rs
Fixes: #623 
We wanted to implement a wait before making attestations which waits for either:
1. A valid block to be proposed to the Beacon node or
2. Passing of 1/3rd of the slot 
For now we only wait 1/3rd of the slot. We will later optimize it to use the events stream to get the head event and wait for valid block as in #640. However setting up the event stream properly will take time so we are moving forward with a simple sleep function that will work.
> feat: use simple 1/3 slot wait

- crates/networking/manager/src/gossipsub/handle.rs
- crates/networking/p2p/src/network/beacon.rs
- crates/networking/p2p/src/network_state.rs
peers would still be connected if disconnected to the swarm
disconnected peer if its disconnected from the swarm
> feat: disconnect peer if disconnected from swarm

- crates/networking/p2p/src/network/beacon.rs
Peers were being pinged before they were connected and it would throw a bunch of logs saying peer not connected skipping peer
made it to Insert peers into peers_to_ping after they are connected
> feat: only insert peers into peers_to_ping after they are connected

- bin/ream/src/main.rs
- crates/common/chain/lean/src/service.rs
Yesterday, there was a new [Rust nightly release](https://rust-analyzer.github.io/thisweek/2025/08/11/changelog-298.html#an-update-on-the-next-trait-solver). This introduced a new solver, which catches bad Rust patterns more accurately.
My last PR (#679) has an anti-pattern (e.g., using `Box::pin` to make it run). It makes our CI (`cargo udeps`) fail since #694. See [the action result](https://github.com/ReamLabs/ream/actions/runs/16900171783/job/47878222193?pr=694).
This PR refactors `LeanChainService` methods by avoiding recursive asynchronous function calls using`mpsc`. (Decoupling the call cycle). Therefore, our `udeps` is much happier right now :)
I also added to log `source_slot` in each vote as this shows the chain finalization much clear.
> refactor: recursive async function issue in `handle_item`

- Cargo.lock
- Cargo.toml
We removed ring from ethereum_hashing to make our crates compile to zkvm's which caused ethereum_hashing to only support sha2 as a backend which is extremely slow on Macos https://github.com/ReamLabs/ream/issues/658
bump ethereum_hashing to the new version with the fix
> perf: bump ethereum_hashing to c14a9ad96436e6b8b631faf49a3666e4558b71ae

- crates/common/validator/lean/src/lib.rs
- crates/common/validator/lean/src/validator.rs
Implement is_proposer based on the proposed validator spec.
https://github.com/unnawut/leanSpec/blob/pqdevnet0-md/docs/client/validator.md
Translated the function to rust
> feat: add is_proposer from the lean spec

- bin/ream/src/main.rs
- crates/common/chain/lean/src/genesis.rs
- crates/common/chain/lean/src/lean_chain.rs
- crates/common/chain/lean/src/service.rs
- crates/common/consensus/lean/src/block.rs
- crates/common/consensus/lean/src/checkpoint.rs
- crates/common/consensus/lean/src/config.rs
- crates/common/consensus/lean/src/lib.rs
- crates/common/consensus/lean/src/state.rs
- crates/common/consensus/lean/src/vote.rs
- crates/common/validator/lean/src/service.rs
- crates/networking/p2p/src/gossipsub/lean/configurations.rs
- crates/networking/p2p/src/gossipsub/lean/message.rs
- crates/networking/p2p/src/gossipsub/lean/topics.rs
- crates/networking/p2p/src/network/lean/mod.rs
Fixes #744, and also matches with current [lean specification](https://github.com/leanEthereum/leanSpec/tree/e9bb80cb5fef3b6a1a2aae009a37cf86f002e431/docs/client) (commit hash: [e9bb80cb5fef3b6a1a2aae009a37cf86f002e431](https://github.com/leanEthereum/leanSpec/commit/e9bb80cb5fef3b6a1a2aae009a37cf86f002e431)).
- Did some double-check with current lean spec.
- Changed `history_length` (= `mcache_len`) to `6`.
- Added docstrings with the specification link.
I'm **quite sure** [the networking part](https://github.com/leanEthereum/leanSpec/blob/main/docs/client/networking.md) would need some changes:
1. Use fork digest instead of `devnet{N}`: Agreed with @KolbyML's [comment](https://github.com/leanEthereum/leanSpec/pull/8#discussion_r2296812658).
2. Add topic for calculating `message-id`: …
> chore: align lean specification with e9bb80

- Cargo.lock
- bin/ream/src/main.rs
- crates/networking/p2p/src/network/lean/mod.rs
- crates/rpc/beacon/src/handlers/peers.rs
- crates/rpc/lean/Cargo.toml
- crates/rpc/lean/src/handlers/mod.rs
- crates/rpc/lean/src/handlers/peer.rs
- crates/rpc/lean/src/lib.rs
- crates/rpc/lean/src/routes/mod.rs
- crates/rpc/lean/src/routes/node.rs
Fixes #714 
- Adds RPC support for fetching peer data for `lean_node`
- Currently 2 endpoints have been added:
- `/lean/v0/node/peers`: to get list of all peers
- `/lean/v0/node/peer_count`: to get connection state
- Tried and tested with local nodes
> feat: add peer rpc for lean

- crates/common/consensus/lean/src/block.rs
- crates/common/consensus/lean/src/state.rs
`LeanState` doesn't have `slot` and `latest_block_header` right now.
Make consistent with the [spec](https://github.com/leanEthereum/leanSpec/blob/main/docs/client/containers.md#state).
`BlockHeader` will be added after https://github.com/leanEthereum/leanSpec/pull/15 is merged.
> chore: add missing fields(slot, latest_block_header) in `LeanState`

- crates/common/api_types/beacon/src/id.rs
- crates/common/validator/beacon/src/beacon_api_client/event.rs
- crates/networking/syncer/src/block_range/block_cache.rs
The node would not run in `no_std` environment, so use `std::fmt::Display` instead of `core::fmt::Display.`
Also did some cosmetics for all over the codebase.
Use `std::fmt::Display`
> chore: use `std::fmt::Display` for consistency

- Cargo.lock
- crates/common/api_types/beacon/Cargo.toml
`cargo udeps` fails: https://github.com/ReamLabs/ream/actions/runs/17431884721/job/49491965211
Delete `actix-web` dependency in `api_types/beacon` crate.
> chore: remove `actix-web` dependency in `api_types/beacon`

- crates/common/consensus/beacon/src/electra/beacon_state.rs
- crates/common/consensus/beacon/src/proposer_slashing.rs
- crates/common/consensus/misc/src/beacon_block_header.rs
- crates/common/operation_pool/src/lib.rs
- crates/rpc/beacon/src/handlers/pool.rs
- crates/rpc/beacon/src/routes/beacon.rs
Fixes: #214 
- Created a new hashset on the op_pool to store the proposer slashings
- GET and POST methods to insert and retrieve them
- Validation against the latest beacon state.
NOTE: Also included a commit which has some code missing from another API endpoint that I worked on `attester_slashings`.
> feat: implementation of /eth/v1/beacon/pool/proposer_slashings

- crates/common/consensus/beacon/src/lib.rs
- crates/common/consensus/beacon/src/sync_committe_selection.rs
- crates/rpc/beacon/src/handlers/validator.rs
fixes: #239 
Since the DVT support is not planned for the upcoming release, the endpoint is supposed to return `501` as suggested in the beacon endpoints specs
> feat: implementation of /eth/v1/validator/sync_committee_selections

- README.md
It could be more clear where users should look to learn more about Ream and set it up
Updating the Read me
> docs: make Ream Book more prevalent in readme

- crates/common/chain/lean/src/lean_chain.rs
- crates/common/chain/lean/src/service.rs
- crates/common/fork_choice/src/lean/mod.rs
- crates/networking/p2p/src/network/lean/mod.rs
- crates/storage/src/db/lean.rs
- crates/storage/src/tables/lean/latest_known_votes.rs
- crates/storage/src/tables/lean/mod.rs
Fixes #817 
- Add prefix `latest_` for `new_votes`/`known_votes`.
- Modify the table to have validator ID as the key.
- Remove unnecessary/redundant functions in the table.
> feat(lean): use validator index as a key of known/new votes

- crates/common/chain/lean/src/lean_chain.rs
- crates/common/consensus/lean/src/state.rs
Fixes: #821 
Moved metric tracking to update_head() as recommended in the issue.
> fix: correct reporting for lean_head_slot metric

- bin/ream/src/main.rs
- crates/common/chain/lean/src/lean_chain.rs
- crates/common/chain/lean/src/lib.rs
- crates/common/chain/lean/src/queue_item.rs
- crates/common/chain/lean/src/service.rs
- crates/storage/src/tables/lean/latest_known_votes.rs
Fixes #787.
Our codebase is mostly came from 3sf-mini, which uses `dependencies` as a queue. However, this implementation is not intuitive as well as complex for real-world devnets.
This PR mainly implements `on_attestation` ([Link](https://github.com/leanEthereum/leanSpec/blob/ee16b19825a1f358b00a6fc2d7847be549daa03b/docs/client/forkchoice.md?plain=1#L279-L312)) function. I did some optimization regarding database transaction using `batch_insert` (thanks to @varun-doshi), so the current code quite deviates from Python spec.
Also, `handle_process_{block|vote}` are now just a wrapper for future p2p validation. By implementing `on_block` and `on_attestation_*` under `LeanChain`, the function becomes much simpler because it removes tackling with synchronization stuffs (e.g., `lock()`...).
> feat(lean): remove `dependencies` in `LeanChainService` & implement `on_attestation` of fork choice specification 

- bin/ream/src/cli/lean_node.rs
- bin/ream/src/cli/mod.rs
> so as per our discussions 3 args are standard:
> 
> 1. —node-id (zeam_0, ream_0...)
> 2. —node_key : path to private key for enr/libp2p
> 3. —data-dir: path to data directory
We need an alias for `private-key-path` flag for better interop
Use `alias` in `clap`
> chore(lean): add alias (`node-key`) for `private-key-path`

- crates/common/consensus/beacon/src/beacon_committee_selection.rs
- crates/common/consensus/beacon/src/lib.rs
- crates/rpc/beacon/src/handlers/validator.rs
- crates/rpc/beacon/src/routes/validator.rs
Fixes #237
implemented GET [/eth/v1/validator/beacon_committee_selections](https://ethereum.github.io/beacon-APIs/#/Validator/submitBeaconCommitteeSelections) endpoint which returns a 501 Not Implemented.
> feat: add beacon committee selection endpoint
