- Cargo.lock
- Cargo.toml
- bin/ream/Cargo.toml
- bin/ream/src/cli/mod.rs
- bin/ream/src/lib.rs
- bin/ream/src/main.rs
Add basic support for command line parser with `clap` .
> feat(bin): add basic cli parser(clap)

- .github/actions/install-mdbook/action.yml
- .github/workflows/book.yml
- .github/workflows/conventional-commits.yml
- .github/workflows/rust.yml
Also some other nits, like aligning `on` sections format of all workflows and `checkout` action versions
> chore(ci): refactor install mdbook code

- Makefile
(btw I am just requesting people I think who might have time to review it, anyone can review this PR if they have time)
It is annoying having to manually type the lint commands so now we can do `make lint`
> feat: add a Makefile for linting `make lint`

- Cargo.lock
- Cargo.toml
- bin/ream/Cargo.toml
- bin/ream/src/main.rs
Add basic structure for `tracing`
> feat: add tracing

- crates/common/consensus/src/attestation_data.rs
- crates/common/consensus/src/fork.rs
- crates/common/consensus/src/lib.rs
implements https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#attestationdata beacon chain type
> feat: implement AttestationData Beacon Chain type

- crates/common/consensus/src/fork.rs
- crates/common/consensus/src/indexed_attestation.rs
- crates/common/consensus/src/lib.rs
- crates/common/consensus/src/signature.rs
**Review this PR first** https://github.com/ReamLabs/ream/pull/23
implements https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#indexedattestation
> feat: implement IndexedAttestation Beacon Chain type

- crates/common/consensus/src/beacon_block_header.rs
- crates/common/consensus/src/deposit_data.rs
- crates/common/consensus/src/eth_1_data.rs
- crates/common/consensus/src/historical_batch.rs
- crates/common/consensus/src/lib.rs
implemented more Beacon Chain types on the way to supporting Beacon State
> feat: implement misc beacon chain types

- crates/common/consensus/src/deneb/beacon_state.rs
- crates/common/consensus/src/fork_choice/helpers/constants.rs
- crates/common/consensus/src/fork_choice/store.rs
- crates/common/consensus/src/helpers.rs
- crates/common/consensus/src/lib.rs
Added more `fork_choice` related functions
[spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/fork-choice.md#store) for reference
> feat : added fork_choice functions

- crates/common/consensus/src/deneb/beacon_state.rs
> feat: implement process_block_header

- crates/common/consensus/src/deneb/beacon_state.rs
implemented the function from this issue https://github.com/ReamLabs/ream/issues/52 
https://ethereum.github.io/consensus-specs/specs/capella/beacon-chain/#new-process_withdrawals
> feat: implemented the process_withdrawals function

- crates/common/consensus/src/deneb/beacon_state.rs
- crates/common/consensus/src/fork_choice/helpers/constants.rs
Implemented the process_bls_to_execution_change function https://github.com/ReamLabs/ream/issues/53
https://ethereum.github.io/consensus-specs/specs/capella/beacon-chain/#new-process_bls_to_execution_change
> feat: implemented the process_bls_to_execution_change function

- crates/common/consensus/src/deneb/beacon_state.rs
- crates/common/consensus/src/validator.rs
> feat: implement process_proposer_slashing

- crates/common/consensus/src/deneb/beacon_state.rs
implemented the https://ethereum.github.io/consensus-specs/specs/capella/beacon-chain/#historical-summaries-updates
> feat: implemented the process_historical_summaries_update function

- crates/common/consensus/src/deneb/beacon_state.rs
- crates/common/consensus/src/misc.rs
- crates/common/consensus/src/predicates.rs
> feat: implement process_attester_slashing

- crates/common/consensus/src/deneb/beacon_state.rs
Implemented the weigh_justification_and_finalization function https://ethereum.github.io/consensus-specs/specs/phase0/beacon-chain/#justification-and-finalization
https://github.com/ReamLabs/ream/issues/77
> feat: implemented the weigh_justification_and_finalization function

- crates/common/consensus/src/misc.rs
fixes https://github.com/ReamLabs/ream/issues/101 , I tested the PR with the test macro @syjn99 added here https://github.com/ReamLabs/ream/pull/108
> fix: compute_shuffled_index computing wrong index

- testing/ef-tests/src/macros/mod.rs
- testing/ef-tests/src/macros/shuffling.rs
- testing/ef-tests/tests/tests.rs
Add shuffling test for `compute_shuffled_index`.
> test: add shuffling test

- crates/common/consensus/src/deneb/beacon_state.rs
I've been working on #70 and #117, and found that our implementation regarding with BLS verification relies on `fast_aggregate_verify`, which is a optimized method suggested by Vitalik. ([Link](https://ethresear.ch/t/fast-verification-of-multiple-bls-signatures/5407))
```python
def process_randao(state: BeaconState, body: BeaconBlockBody) -> None:
epoch = get_current_epoch(state)
proposer = state.validators[get_beacon_proposer_index(state)]
signing_root = compute_signing_root(epoch, get_domain(state, DOMAIN_RANDAO))
assert bls.Verify(proposer.pubkey, signing_root, body.randao_reveal)
mix = xor(get_randao_mix(state, epoch), hash(body.randao_reveal))
state.randao_mixes[epoch % EPOCHS_PER_HISTORICAL_VECTOR] = mix
```
For the most of case including `process_randao`, it isn't necessary and …
> fix: not to use `fast_aggregate_verify` for all BLS verification

- crates/common/consensus/src/deneb/beacon_block_body.rs
- crates/common/consensus/src/execution_engine/mod.rs
- crates/common/consensus/src/execution_engine/rpc_types/engine_get_payloadv1.rs
- crates/common/consensus/src/execution_engine/rpc_types/mod.rs
- crates/common/consensus/src/execution_engine/utils.rs
- crates/common/consensus/src/kzg_commitment.rs
This is required to implement process_execution_payload() https://github.com/ReamLabs/ream/issues/51
implementing json engine api rpc calls
> feat: implement engine_getPayloadV3 api rpc call

- crates/common/consensus/src/deneb/beacon_state.rs
- crates/common/consensus/src/execution_engine/mod.rs
- crates/common/consensus/src/execution_engine/rpc_types/execution_payload.rs
- crates/common/consensus/src/execution_engine/rpc_types/payload_status.rs
- crates/common/consensus/src/fork_choice/helpers/constants.rs
implemented process_execution_payload, notify_new_payload, verify_and_notify_new_payload functions
process_execution_payload()  issue: https://github.com/ReamLabs/ream/issues/51
https://ethereum.github.io/consensus-specs/specs/deneb/beacon-chain/#modified-process_execution_payload
notify_new_payload()
https://ethereum.github.io/consensus-specs/specs/deneb/beacon-chain/#modified-notify_new_payload
verify_and_notify_new_payload()
https://ethereum.github.io/consensus-specs/specs/deneb/beacon-chain/#modified-verify_and_notify_new_payload
> feat: implemented process_execution_payload, notify_new_payload, verify_and_notify_new_payload functions

- crates/common/consensus/src/deneb/beacon_state.rs
state_transition() Issue: https://github.com/ReamLabs/ream/issues/88
https://ethereum.github.io/consensus-specs/specs/phase0/beacon-chain/#beacon-chain-state-transition-function
Will add test in follow up PR https://github.com/ReamLabs/ream/issues/141
process_block() Issue: https://github.com/ReamLabs/ream/issues/127
https://ethereum.github.io/consensus-specs/specs/capella/beacon-chain/#block-processing
> feat: implement process_block(), state_transition() functions

- Cargo.lock
- Cargo.toml
- crates/common/consensus/Cargo.toml
- crates/common/consensus/src/deneb/beacon_state.rs
- crates/common/consensus/src/execution_engine/engine_trait.rs
- crates/common/consensus/src/execution_engine/mock_engine.rs
- crates/common/consensus/src/execution_engine/mod.rs
- testing/ef-tests/Cargo.toml
- testing/ef-tests/src/macros/operations.rs
- testing/ef-tests/tests/tests.rs
added test for process_execution_payload and implement MockExecutionEngine
Issue: https://github.com/ReamLabs/ream/issues/140
> feat: added test for process_execution_payload and implement MockExecutionEngine

- bin/ream/src/main.rs
- crates/common/consensus/src/deneb/beacon_state.rs
fix log level and message description
> chore: use accurate log level to output message

- crates/common/consensus/src/deneb/beacon_state.rs
- testing/ef-tests/tests/tests.rs
Fixed the process_registry_updates() function to match the spec
Issue: https://github.com/ReamLabs/ream/issues/164
> feat: Implement final testing for process_registry_updates()

- crates/common/consensus/src/deneb/beacon_state.rs
- testing/ef-tests/src/macros/mod.rs
- testing/ef-tests/src/macros/sanity_slots.rs
- testing/ef-tests/tests/tests.rs
Implemented macro for sanity_slots and added testing for process_slots()
Spec: https://github.com/ethereum/consensus-specs/blob/8fa1aaae5eaca6d9bdcea99658e834963557c20d/tests/formats/sanity/slots.md
> feat: Implemented macro for sanity_slots and added testing for process_slots()

- crates/common/consensus/src/execution_engine/mock_engine.rs
- testing/ef-tests/src/macros/mod.rs
- testing/ef-tests/src/macros/sanity_blocks.rs
- testing/ef-tests/tests/tests.rs
Implemented sanity_blocks macro and testing for state_transition()
Spec: https://github.com/ethereum/consensus-specs/blob/8fa1aaae5eaca6d9bdcea99658e834963557c20d/tests/formats/sanity/blocks.md
> feat: Implemented sanity_blocks macro and testing for state_transition()

- testing/ef-tests/src/macros/epoch_processing.rs
- testing/ef-tests/src/macros/operations.rs
- testing/ef-tests/src/macros/rewards.rs
- testing/ef-tests/src/macros/sanity_blocks.rs
- testing/ef-tests/src/macros/sanity_slots.rs
- testing/ef-tests/tests/tests.rs
Small fix removed unneeded paste and removed debug print statements that where no longer needed
> test: removed unneeded paste and cleaned up macros

- .github/workflows/riscv.yml
- Cargo.lock
- Cargo.toml
- bin/ream/Cargo.toml
- bin/ream/src/cli/mod.rs
- bin/ream/src/main.rs
- crates/storage/Cargo.toml
- crates/storage/src/db.rs
- crates/storage/src/dir.rs
- crates/storage/src/errors.rs
- crates/storage/src/lib.rs
- crates/storage/src/tables/beacon_state.rs
- crates/storage/src/tables/mod.rs
@Vid201 ping for review
I am initialing the storage crate, I also added a small demo for showing how we would create a table
> feat: initialize db

- CONTRIBUTING.md
- Makefile
Here is a `CONTRIBUTING.md` based off Reth's, this should help new contributors onboard
> docs: add CONTRIBUTING.md

- crates/rpc/src/handlers/genesis.rs
- crates/rpc/src/handlers/mod.rs
@varun-doshi you forgot "data" around the genesis json!(). I didn't catch it too during review, but going forward we should do it like this!
> fix(rpc): forgot "data": T for genesis rpc

- Cargo.lock
- Cargo.toml
- bin/ream/Cargo.toml
- bin/ream/src/cli/mod.rs
- crates/common/node/Cargo.toml
- crates/common/node/build.rs
- crates/common/node/src/lib.rs
- crates/common/node/src/version.rs
@varun-doshi once this is merged rebase your PR and do
in your route.rs file for the node rpc
```
pub struct Version {
version: String
}
impl Version {
pub fn new() -> Self {
Self { version: ream_node_version() }
}
}
```
Then you can do `Data::json(Version::new())`
> feat: add ream version info

- Cargo.lock
- crates/rpc/Cargo.toml
- crates/rpc/src/handlers/mod.rs
- crates/rpc/src/handlers/version.rs
- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/routes/mod.rs
- crates/rpc/src/routes/node.rs
Closes #179 
Run node:
```
cargo run node
```
Make a `GET` request to:
```
/eth/v1/node/version
```
> feat: add `/node/version` endpoint

- book/SUMMARY.md
> docs(book): add installation and changelog pages to book navigation

- crates/storage/src/db.rs
- crates/storage/src/tables/beacon_block.rs
- crates/storage/src/tables/mod.rs
added the beacon block table to the database
> feat: add beacon block table to the database

- crates/common/consensus/src/checkpoint.rs
- crates/storage/src/db.rs
- crates/storage/src/tables/checkpoint_states.rs
- crates/storage/src/tables/mod.rs
fixes https://github.com/ReamLabs/ream/issues/274
added the checkpoint_states table to the database
> feat: add database table for checkpoint_states

- crates/storage/src/db.rs
- crates/storage/src/tables/latest_messages.rs
- crates/storage/src/tables/mod.rs
fixes https://github.com/ReamLabs/ream/issues/273
added the latest messages table to the database
> feat: add latest messages table to the database

- crates/storage/src/db.rs
- crates/storage/src/tables/block_timeliness.rs
- crates/storage/src/tables/mod.rs
fixes https://github.com/ReamLabs/ream/issues/275
added the block_timeliness table to the database
> feat: add database table for block_timeliness

- crates/storage/src/db.rs
- crates/storage/src/tables/mod.rs
- crates/storage/src/tables/unrealized_finalized_checkpoint.rs
fixes https://github.com/ReamLabs/ream/issues/278
added the unrealized_finalized_checkpoint table to the database
> feat: add unrealized_finalized_checkpoint table to the database 

- crates/storage/src/db.rs
- crates/storage/src/tables/mod.rs
- crates/storage/src/tables/unrealized_justified_checkpoint.rs
fixes https://github.com/ReamLabs/ream/issues/279
added the unrealized_justified_checkpoint table to the database
> feat: add unrealized_justified_checkpoint table to the database

- crates/storage/src/db.rs
- crates/storage/src/tables/finalized_checkpoint.rs
- crates/storage/src/tables/mod.rs
fixes https://github.com/ReamLabs/ream/issues/280
added the finalized_checkpoint table to the database
> feat: add finalized_checkpoint table to the database

- crates/storage/src/db.rs
- crates/storage/src/tables/justified_checkpoint.rs
- crates/storage/src/tables/mod.rs
fixes https://github.com/ReamLabs/ream/issues/281
added the justified_checkpoint table to the database
> feat: add justified_checkpoint table to the database

- crates/storage/src/db.rs
- crates/storage/src/tables/genesis_time.rs
- crates/storage/src/tables/mod.rs
fixes https://github.com/ReamLabs/ream/issues/282
added the genesis_time table to the database
> feat: add genesis_time table to the database

- crates/storage/src/db.rs
- crates/storage/src/tables/mod.rs
- crates/storage/src/tables/time.rs
fixes https://github.com/ReamLabs/ream/issues/283
added the time table to the database
> feat: add time table to the database

- crates/common/fork_choice/src/handlers.rs
fixes https://github.com/ReamLabs/ream/issues/301
https://ethereum.github.io/consensus-specs/specs/phase0/fork-choice/#on_attester_slashing
> feat: implement on_attester_slashing fork choice function

- crates/common/fork_choice/src/handlers.rs
https://ethereum.github.io/consensus-specs/specs/phase0/fork-choice/#on_tick
> feat: Implement on_tick fork choice function

- crates/common/fork_choice/src/handlers.rs
fixes https://github.com/ReamLabs/ream/issues/295
https://ethereum.github.io/consensus-specs/specs/phase0/fork-choice/#on_attestation
> feat: implement on_attestation fork choice function

- Cargo.lock
- bin/ream/src/main.rs
- crates/crypto/bls/src/errors.rs
- crates/crypto/bls/src/pubkey.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/handlers/mod.rs
- crates/rpc/src/handlers/state.rs
- crates/rpc/src/handlers/validator.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/routes/mod.rs
- crates/rpc/src/types/errors.rs
- crates/rpc/src/types/id.rs
- crates/rpc/src/types/mod.rs
- crates/rpc/src/utils/error.rs
- crates/storage/src/tables/slot_index.rs
Implemented `/eth/v1/beacon/states/{state_id}/validators/{validator_id}`
Closes #188
> feat: implement `getStateValidator` endpoint

- crates/rpc/src/handlers/mod.rs
- crates/rpc/src/handlers/randao.rs
- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/routes/mod.rs
- crates/rpc/src/types/mod.rs
- crates/rpc/src/types/query.rs
```
cargo run node
```
```
/states/<state_id>/randao
```
With optional epoch query:
```
/states/<state_id>/randao?epoch=1234
```
Closes #193
> feat: implement /randao endpoint

- crates/rpc/src/handlers/fork.rs
- crates/rpc/src/handlers/mod.rs
- crates/rpc/src/routes/beacon.rs
```
cargo run node
```
```
/states/{state_id}/fork
```
Closes #185
> feat: implement states/{state_id}/fork endpoint

- crates/rpc/src/handlers/checkpoint.rs
- crates/rpc/src/handlers/mod.rs
- crates/rpc/src/routes/beacon.rs
```
cargo run node
```
```
/states/{state_id}/finality_checkpoints
```
Closes #186
> feat: implement /finality_checkpoints endpoint

- crates/rpc/src/handlers/block.rs
- crates/rpc/src/handlers/mod.rs
- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/types/mod.rs
- crates/rpc/src/types/response.rs
- crates/storage/src/tables/beacon_block.rs
```
cargo run node
```
```
/blocks/<block_id>/root
```
Closes #201
> feat: implement /<block>/root endpoint

- crates/common/fork_choice/src/handlers.rs
Implements the get_forkchoice_store function
needed inorder to implment this issue https://github.com/ReamLabs/ream/issues/169
> feat: implement get_forkchoice_store function

- crates/rpc/src/handlers/block.rs
- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/types/response.rs
Closes #205 
-This pull request added handler for Beacon API endpoint GET /eth/v1/beacon/blocks/{block_id}/rewards
> Implement/eth/v1/beacon/rewards/blocks/{block id}

- crates/rpc/src/handlers/block.rs
- crates/rpc/src/routes/beacon.rs
- Close https://github.com/ReamLabs/ream/issues/200
- This pull request added handler for Beacon API endpoint `GET /eth/v2/beacon/blocks/{block_id}`
> feat: implement /eth/v2/beacon/blocks/{block_id}

- crates/rpc/src/handlers/validator.rs
- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/types/errors.rs
- crates/rpc/src/types/mod.rs
- crates/rpc/src/types/query.rs
- crates/rpc/src/types/request.rs
- crates/rpc/src/utils/error.rs
Resolve #187 
-Creates an endpoint to return spec configuration from GET with optional id and status queries 
- Creates an endpoint for post request for validators 
- I created a new file request.rs to make struct for post request
> feat: implement states/{state_id}/validators

- crates/common/consensus/src/beacon_block_header.rs
- crates/common/consensus/src/blob_sidecar.rs
- crates/common/consensus/src/electra/beacon_block.rs
- crates/common/consensus/src/execution_engine/rpc_types/get_blobs.rs
- crates/rpc/src/handlers/blob_sidecar.rs
- crates/rpc/src/handlers/header.rs
- crates/rpc/src/handlers/mod.rs
- crates/rpc/src/routes/beacon.rs
- crates/rpc/src/types/query.rs
> feat: implement /eth/v1/beacon/blob_sidecars/{block_id}

- testing/ef-tests/tests/tests.rs
Implemented missing process_sync_aggregate test https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/operations
Fixes https://github.com/ReamLabs/ream/issues/115
> feat: Implemented process_sync_aggregate test

- Cargo.lock
- Cargo.toml
- crates/common/node/src/version.rs
- crates/networking/discv5/src/discovery.rs
- crates/networking/p2p/Cargo.toml
- crates/networking/p2p/src/lib.rs
- crates/networking/p2p/src/network.rs
- crates/networking/p2p/src/req_resp/configurations.rs
- crates/networking/p2p/src/req_resp/error.rs
- crates/networking/p2p/src/req_resp/handler.rs
- crates/networking/p2p/src/req_resp/inbound_protocol.rs
- crates/networking/p2p/src/req_resp/messages/goodbye.rs
- crates/networking/p2p/src/req_resp/messages/meta_data.rs
- crates/networking/p2p/src/req_resp/messages/mod.rs
- crates/networking/p2p/src/req_resp/messages/ping.rs
- crates/networking/p2p/src/req_resp/messages/status.rs
- crates/networking/p2p/src/req_resp/mod.rs
- crates/networking/p2p/src/req_resp/outbound_protocol.rs
- crates/networking/p2p/src/req_resp/protocol_id.rs
- crates/networking/p2p/src/req_resp/utils.rs
fixes https://github.com/ReamLabs/ream/issues/92
> Add initial res/resp domain support

- Cargo.lock
- crates/common/validator/Cargo.toml
- crates/common/validator/src/execution_requests.rs
fixes https://github.com/ReamLabs/ream/issues/401
Added another function from the electra spec 
Once most of the validator functions are done, we would need to make a few PR's to run tests on the functionality.
> feat: implement prepare_execution_payload

- crates/common/fork_choice/src/store.rs
Fixes: https://github.com/ReamLabs/ream/issues/422
https://ethereum.github.io/consensus-specs/specs/phase0/fork-choice/#get_filtered_block_tree
https://ethereum.github.io/consensus-specs/specs/phase0/fork-choice/#get_head
> feat: implemented get_head() and get_filtered_block_tree()

- crates/networking/p2p/src/gossipsub/error.rs
- crates/networking/p2p/src/gossipsub/message.rs
- crates/networking/p2p/src/gossipsub/mod.rs
- crates/networking/p2p/src/gossipsub/topics.rs
- crates/networking/p2p/src/network.rs
This PR creates gossipsub message structs/enums and handles gossip topic beacon block.
Closes #378
> feat: implement gossip topic beacon_block

- Cargo.lock
- crates/networking/p2p/Cargo.toml
- crates/networking/p2p/src/gossipsub/message.rs
- crates/networking/p2p/src/network.rs
Fixes: https://github.com/ReamLabs/ream/issues/382
Adding attester_slashing gossip topic
> feat: implement gossip topic attester_slashing

- Cargo.lock
- Cargo.toml
- crates/common/validator/Cargo.toml
- crates/common/validator/src/aggregate_and_proof.rs
- crates/networking/p2p/Cargo.toml
- crates/networking/p2p/src/gossipsub/message.rs
- crates/networking/p2p/src/gossipsub/topics.rs
- crates/networking/p2p/src/network.rs
Fixes: https://github.com/ReamLabs/ream/issues/379
Adding aggregate_and_proof gossip topic
> feat: implement gossip topic aggregate_and_proof

- crates/common/consensus/src/blob_sidecar.rs
- crates/common/consensus/src/execution_engine/rpc_types/get_blobs.rs
- crates/networking/p2p/Cargo.toml
- crates/networking/p2p/src/gossipsub/message.rs
- crates/networking/p2p/src/network.rs
https://github.com/ReamLabs/ream/issues/389
Adding blob_sidecar gossip topic
> feat: implement gossip topic blob_sidecar

- crates/networking/p2p/src/gossipsub/message.rs
- crates/networking/p2p/src/network.rs
Fixes: https://github.com/ReamLabs/ream/issues/383
Adding beacon_attestation gossip topic
> feat: implement gossip topic beacon_attestation

- crates/common/consensus/src/sync_committee.rs
- crates/networking/p2p/src/gossipsub/message.rs
- crates/networking/p2p/src/network.rs
Fixes: https://github.com/ReamLabs/ream/issues/385
Adding sync_committee gossip topic
> feat: implement gossip topic sync_committee

- crates/common/validator/src/contribution_and_proof.rs
- crates/common/validator/src/lib.rs
- crates/networking/p2p/src/gossipsub/message.rs
- crates/networking/p2p/src/network.rs
Fixes: https://github.com/ReamLabs/ream/issues/384
Adding sync_committee_contribution_and_proof gossip topic
> feat: implement gossip topic sync_committee_contribution_and_proof

- crates/networking/p2p/src/gossipsub/message.rs
- crates/networking/p2p/src/network.rs
Fixes #381 
Add `ProposerSlashing` to GossipSub messages
> feat: implement ProposerSlashing over gossipsub

- crates/common/consensus/src/electra/beacon_state.rs
- crates/common/consensus/src/eth_1_data.rs
- testing/ef-tests/tests/tests.rs
fixes https://github.com/ReamLabs/ream/issues/421
Ended up adding it as a beacon state method due to the fields it uses.
> feat: Added get_eth1_vote

- crates/common/execution_engine/src/lib.rs
Fixes: https://github.com/ReamLabs/ream/issues/467
> feat: Implement engine api eth_getBlockByNumber

- Cargo.lock
- crates/common/execution_engine/Cargo.toml
- crates/common/execution_engine/src/lib.rs
Fixes: https://github.com/ReamLabs/ream/issues/468
> feat: Implement engine api eth_getLogs

- crates/common/execution_engine/src/lib.rs
Fixes: https://github.com/ReamLabs/ream/issues/464
> feat: Implement engine api eth_chainId

- crates/common/execution_engine/src/lib.rs
Fixes: https://github.com/ReamLabs/ream/issues/463
> feat: Implement engine api eth_call

- crates/common/execution_engine/src/lib.rs
Fixes: https://github.com/ReamLabs/ream/issues/465
> feat: Implement engine api eth_getCode

- crates/common/validator/src/beacon_api_client/mod.rs
fixes https://github.com/ReamLabs/ream/issues/482
Fairly small PR. I made it in the same style as get_proposer_duties. With it, you should be able to pass in a list of validator_indicies to get the duties.
Once the validator is up and running(as well as a beacon or beam node), we need to add integration tests using endpoints like this.
> feat: connect POST duties/attester/{epoch} to the validator

- crates/networking/manager/src/service.rs
We were failing to create the reply status message
If we can't build the head due to not having enough history, just return our head as the finalized root, in the case I am testing that is the only root we have anyways
> fix: failing to create status reply on non-fully synced db

- crates/networking/p2p/src/network.rs
- crates/networking/p2p/src/req_resp/handler.rs
- crates/networking/p2p/src/req_resp/mod.rs
- The logs were so noisy I couldn't see anything
- We had a few problems in our peer connection logic
- remove too noisy logs
- clean up peer connection logic
> chore: clean up noisy logs + clean up peer connection code

- crates/networking/discv5/src/discovery.rs
Fixes: https://github.com/ReamLabs/ream/issues/626
It was implemented by only querying with the predicate of eth2
> feat: only query peers on the same network, increases connected rate 6x

- .github/PULL_REQUEST_TEMPLATE.md
Our previous PR template was unclear, which lead to suboptimal PR descriptions
Simplify it but also make the description more intentional. Using what is wrong focuses the description on a problem within the codebase, whereas `What are you trying to achieve?` asks a very different question focusing on the writer's goals, but what we are interested in is the problem with the codebase
> chore: make pull request template more clear

- Cargo.lock
- bin/ream/src/main.rs
- crates/common/consensus/Cargo.toml
- crates/common/consensus/src/electra/beacon_state.rs
- crates/common/fork_choice/Cargo.toml
- crates/common/fork_choice/src/handlers.rs
- crates/networking/discv5/src/discovery.rs
- crates/networking/manager/src/gossipsub/handle.rs
- crates/networking/manager/src/p2p_sender.rs
- crates/networking/p2p/src/channel.rs
- crates/networking/p2p/src/network.rs
- crates/networking/p2p/src/req_resp/configurations.rs
- crates/networking/p2p/src/req_resp/error.rs
- crates/networking/p2p/src/req_resp/handler.rs
- crates/networking/p2p/src/req_resp/mod.rs
- crates/networking/syncer/src/block_range/block_cache.rs
- crates/networking/syncer/src/block_range/mod.rs
- crates/networking/syncer/src/block_range/peer_manager.rs
- crates/networking/syncer/src/block_range/peer_range_downloader.rs
The network code wasn't robust enough to reliably forward sync
- Add a few connection/callback timeouts
- reduce noisy logs
> fix: up network code to get forward syncer more reliable

- crates/common/consensus/beacon/src/single_attestation.rs
- crates/common/consensus/misc/src/attestation_data.rs
- crates/common/consensus/misc/src/constants.rs
- crates/networking/manager/src/gossipsub/handle.rs
- crates/networking/manager/src/gossipsub/validate/beacon_attestation.rs
- crates/networking/manager/src/gossipsub/validate/blob_sidecar.rs
- crates/networking/manager/src/gossipsub/validate/mod.rs
- crates/networking/p2p/src/gossipsub/message.rs
- crates/storage/src/cache.rs
Fixes: https://github.com/ReamLabs/ream/issues/599
https://ethereum.github.io/consensus-specs/specs/phase0/p2p-interface/#beacon_attestation_subnet_id
https://ethereum.github.io/consensus-specs/specs/deneb/p2p-interface/#beacon_attestation_subnet_id
https://ethereum.github.io/consensus-specs/specs/electra/p2p-interface/#beacon_attestation_subnet_id
> feat: gossipsub validate and forward: beacon_attestation_{subnet_id}

- crates/networking/manager/src/gossipsub/handle.rs
- crates/networking/p2p/src/gossipsub/message.rs
Fixes #380 
Adds the `VoluntaryExit` gossipsub message
> feat: gossipsub topic: voluntary exit

- crates/common/validator/beacon/src/sync_committee.rs
- crates/networking/manager/src/gossipsub/handle.rs
- crates/networking/manager/src/gossipsub/validate/mod.rs
- crates/networking/manager/src/gossipsub/validate/sync_committee.rs
- crates/networking/p2p/src/gossipsub/message.rs
- crates/storage/src/cache.rs
Fixes: https://github.com/ReamLabs/ream/issues/598
https://ethereum.github.io/consensus-specs/specs/altair/p2p-interface/#sync_committee_subnet_id
> feat: gossipsub validate and forward: sync_committee_{subnet_id}

- crates/networking/manager/src/gossipsub/handle.rs
- crates/networking/manager/src/gossipsub/validate/mod.rs
- crates/networking/manager/src/gossipsub/validate/proposer_slashing.rs
- crates/storage/src/cache.rs
Fixes: https://github.com/ReamLabs/ream/issues/592
https://ethereum.github.io/consensus-specs/specs/phase0/p2p-interface/#proposer_slashing
> feat: gossipsub validate and forward: proposer_slashing

- crates/networking/manager/src/gossipsub/handle.rs
- crates/networking/manager/src/gossipsub/validate/attester_slashing.rs
- crates/networking/manager/src/gossipsub/validate/mod.rs
- crates/storage/src/cache.rs
Fixes: https://github.com/ReamLabs/ream/issues/593
https://ethereum.github.io/consensus-specs/specs/phase0/p2p-interface/#attester_slashing
> feat: gossipsub validate and forward: attester_slashing

- crates/common/chain/lean/src/staker.rs
we where calling anyhow::anyhow( everytime it was used
Imports anyhow
> feat: Import anyhow instead of adding it everytime its used

- crates/rpc/beacon/src/handlers/light_client.rs
- crates/rpc/beacon/src/routes/beacon.rs
Fixes #211 
implemented [/eth/v1/beacon/light_client/optimistic_update of BeaconAPI](https://ethereum.github.io/beacon-APIs/#/Beacon/getLightClientOptimisticUpdate)
> feat: add light client optimistic update endpoint to Beacon APIs

- README.md
Update beam chain to lean chain (added consensus when needed)
Check the title on the Video attached. Do we change that too ?
> chore: update README to Lean chain from Beam chain

- Cargo.lock
- Makefile
- testing/gossip-validation/Cargo.toml
- testing/gossip-validation/tests/validate_block.rs
Test to cover different cases for validate_beacon_block function was needed #635
Added more tests to check other cases
added some tests, would add some more test (covering positive side of validate_beacon_block fn) in new pr
> test: added more test for validate_beacon_block 

- crates/crypto/pqc/src/hashsig/mod.rs
> refactor: imports go after mod in pqc crate

- crates/common/chain/lean/src/service.rs
Fixes: https://github.com/ReamLabs/ream/issues/730
if it processes successfully, it publishes if it fails it logs an error
> feat: Don't propagate lean block/vote if processing failed

- crates/networking/manager/src/gossipsub/handle.rs
- crates/networking/manager/src/gossipsub/validate/mod.rs
- crates/networking/manager/src/gossipsub/validate/sync_committee_contribution_and_proof.rs
- crates/storage/src/cache.rs
fixes: #594
Once verify the validation logic followed for the `check_sync_committee` mainly
> feat: implemenation of gossipsub validate and forward: sync_committee_contribution_and_proof

- Cargo.lock
- crates/common/chain/lean/src/genesis.rs
- crates/common/chain/lean/src/lean_chain.rs
- crates/common/chain/lean/src/service.rs
- crates/common/chain/lean/src/slot.rs
- crates/common/consensus/lean/Cargo.toml
- crates/common/consensus/lean/src/state.rs
- crates/common/consensus/misc/src/constants/lean.rs
- crates/common/validator/lean/src/service.rs
Fixing multiple issues found in interop
1. genesis generation logic
2. use `Bitlist` for `justification_slots`
3. correctly calculate slot (not to start with `1`)
Use https://github.com/ReamLabs/local-pq-devnet/tree/zeam-integration
> fix(lean): consensus issues (use `Bitlist` for `justification_slots`, etc.)
